_: &steps
  - checkout
  - run:
      name: Bundle
      command: gem install bundler && bundle install
  - run:
      name: RSpec
      command: bundle exec rspec

version: 2
jobs:
  ruby-3.1:
    docker:
      - image: cimg/ruby:3.1
    steps: *steps
  ruby-3.0:
    docker:
      - image: cimg/ruby:3.0
    steps: *steps
  ruby-2.7:
    docker:
      - image: cimg/ruby:2.7
    steps: *steps
  ruby-2.6:
    docker:
      - image: cimg/ruby:2.6
    steps: *steps
  ruby-2.5:
    docker:
      - image: cimg/ruby:2.5
    steps: *steps
  ruby-2.4:
    docker:
      - image: cimg/ruby:2.4
    steps: *steps
  ruby-2.3:
    docker:
      - image: circleci/ruby:2.3
    steps: *steps
  jruby-9.3:
    docker:
      - image: circleci/jruby:9.3
    steps: *steps
  jruby-9.2:
    docker:
      - image: circleci/jruby:9.2
    steps: *steps
  jruby-9.1:
    docker:
      - image: circleci/jruby:9.1
    steps: *steps
  jruby-9.0:
    docker:
      - image: circleci/jruby:9
    steps: *steps
workflows:
  version: 2
  rubies:
    jobs:
      - ruby-3.1
      - ruby-3.0
      - ruby-2.7
      - ruby-2.6
      - ruby-2.5
      - ruby-2.4
      - ruby-2.3
      - jruby-9.3
      - jruby-9.2
      - jruby-9.1
      - jruby-9.0
